[program:updates-server]
command=/usr/bin/env node server.js
directory=/home/otaupdates/custom-ota-updates/expo-updates-server
user=otaupdates
autostart=true
autorestart=true
startsecs=10
stopasgroup=true
killasgroup=true

; Environment for HTTPS server + expo manifest signing
environment=NODE_ENV="production",PORT="3000",HOSTNAME="https://otaupdates.huayra.com.ar:3000",ASSETS_BASE_URL="https://otaupdates.huayra.com.ar:3000/updates/assets",PRIVATE_KEY_PATH="code-signing-keys/private-key.pem",SSL_CERT_PATH="/home/otaupdates/ssl/ssl.cert",SSL_KEY_PATH="/home/otaupdates/ssl/ssl.key",SSL_CA_PATH="/home/otaupdates/ssl/ssl.ca"

stdout_logfile=/home/otaupdates/custom-ota-updates/expo-updates-server/logs/supervisor/updates-server.out.log
stderr_logfile=/home/otaupdates/custom-ota-updates/expo-updates-server/logs/supervisor/updates-server.err.log
stdout_logfile_maxbytes=20MB
stderr_logfile_maxbytes=20MB
stdout_logfile_backups=5
stderr_logfile_backups=5
